# Generated by Django 3.2.3 on 2021-05-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.movie'),
            preserve_default=False,
        ),
    ]
