# Generated by Django 3.2.3 on 2021-05-31 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
